language: cpp

#before_script:
#  - sudo apt-get update -qq
#  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev

before_install:
  - sudo add-apt-repository -y ppa:nschloe/boost-nightly
  - sudo apt-get update -qq
install:
  # - sudo apt-get install libboost1.60-all-dev
  - sudo apt-get install libboost-serialization1.60-dev libboost-atomic1.60-dev libboost-chrono1.60-dev libboost-date-time1.60-dev libboost-thread1.60-dev libboost-system1.60-dev libboost-test1.60-dev
  # - sudo apt-get install libboost1.64-all-dev (also tried)

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - doxygen

script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake -D ENABLE_COVERAGE:BOOL=TRUE . 
  - cmake --build . -- -j2 
  - ctest -j2
#  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-5

