language: cpp

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - doxygen

script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake -D ENABLE_COVERAGE:BOOL=TRUE . 
  - cmake --build . -- -j2 
  - ctest -j2
#  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-5

